### ISSUE TITLE
Fehlende Links bei Suchergebnissen

### ISSUE THREAD

**Issue by contaoacademy** [smohring/cearch-pro-bundle#1]
Bei den Suchergebnissen fehlen leider die Links. Es werden leere href-Attribute ausgegeben.
Getestet mit Contao 4.4.21

**Comment by akroii** [comment]
Der Fehler müsste in der aktuellen Version gefixxt sein.

[https://github.com/smohring/cearch-pro-bundle/commit/8db7fde42ac014877f47037404a9a991d256bd83](https://github.com/smohring/cearch-pro-bundle/commit/8db7fde42ac014877f47037404a9a991d256bd83)

**Comment by smohring** [comment]
MIt der info von @akroii mach ich das Ticket mal zu. Werde die Extension demnächst selbst wieder verwenden und dann ggf. ein neues Release mit Bugfixes bereitstellen.
