### ISSUE TITLE
"image" => null

### ISSUE THREAD

**Issue by sbstn2** [smohring/cearch-pro-bundle#3]
Hallo, ich habe die Erweiterung nun in Contao 4.4.32 Managed Edition eingebaut. Sie funktioniert auch soweit. Nur leider werden die Bilder nicht ausgegeben. Wenn ich mir alle möglichen Variablen der Erweiterung durch hinzufügen von <?php $this->showTemplateVars(); ?> im search_default.html5 Template anzeigen lasse, dann erscheint dort nur "image" => null.
Handelt es sich um eine Inkompatibilität oder habe ich etwas übersehen?
Bei den betreffenden Nachrichten habe ich jeweils Bilder hinterlegt.

Habe gerade noch festgestellt, dass die Suche meist manche Begriffe gar nicht findet, obwohl sie auf der Seite vorhanden sind. Vorhin hat die Suche dann die Begriffe plötzlich gefunden und jetzt erscheint wieder: "No matches"

**Comment by smohring** [comment]
Ist schon eine Weile her, aber wenn ich mich recht entsinne, werden wenn vorhanden og:image aus dem head der Seite beim aufbauen des Suchindex ausgewertet und gespeichert.

z.B.

`<meta property="og:image" content="https://mysite.de/myimage.jpg"/>
`
Im Template ist dann das entsprechende Bild verfügbar. Würde ich heute ggf. etwas anders bauen (unabhängig von oh:image).
