### ISSUE TITLE
Error when trying to install on Version 4.7.1

### ISSUE THREAD

**Issue by lucasdidthis** [smohring/cearch-pro-bundle#4]
When I try to install the extension within the Contao Manager on a System with Version 4.7.1 I always get an error.

Anyone else having trouble?

Thanks in advance, 
Lucas

**Comment by lucasdidthis** [comment]
Don't know, if that's relevant, but the Contao Manager is Version 1.1.3

**Comment by fritzmg** [comment]
You should post the error ... otherwise this is not helpful ;)

**Comment by lucasdidthis** [comment]
Danke für den Hinweis, das ist der Fehlercode, den die Console ausspuckt:

# Process terminated with exit code 0
# Result: OK

> Resolving dependencies using Composer Cloud v2.0.5

[358.9MiB/4.22s] Loading composer repositories with package information
[359.2MiB/4.32s] Updating dependencies
[1858.4MiB/41.76s] Your requirements could not be resolved to an installable set of packages.
[1858.4MiB/41.77s] 
  Problem 1
    - Conclusion: don't install smohring/cearch-pro-bundle 1.1.2
    - Conclusion: don't install smohring/cearch-pro-bundle 1.1.1
    - Conclusion: don't install symfony/cache v4.2.4
    - symfony/framework-bundle v3.3.0 requires symfony/cache ~3.3 -> satisfiable by symfony/cache[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - symfony/framework-bundle v3.3.1 requires symfony/cache ~3.3 -> satisfiable by symfony/cache[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - symfony/framework-bundle v3.3.10 requires symfony/cache ~3.3 -> satisfiable by symfony/cache[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - symfony/framework-bundle v3.3.11 requires symfony/cache ~3.3 -> satisfiable by symfony/cache[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - symfony/framework-bundle v3.3.12 requires symfony/cache ~3.3 -> satisfiable by symfony/cache[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - symfony/framework-bundle v3.3.13 requires symfony/cache ~3.3 -> satisfiable by symfony/cache[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - symfony/framework-bundle v3.3.14 requires symfony/cache ~3.3 -> satisfiable by symfony/cache[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - symfony/framework-bundle v3.3.15 requires symfony/cache ~3.3 -> satisfiable by symfony/cache[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - symfony/framework-bundle v3.3.16 requires symfony/cache ~3.3 -> satisfiable by symfony/cache[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - symfony/framework-bundle v3.3.17 requires symfony/cache ~3.3 -> satisfiable by symfony/cache[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - symfony/framework-bundle v3.3.18 requires symfony/cache ~3.3 -> satisfiable by symfony/cache[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - symfony/framework-bundle v3.3.2 requires symfony/cache ~3.3 -> satisfiable by symfony/cache[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - symfony/framework-bundle v3.3.3 requires symfony/cache ~3.3 -> satisfiable by symfony/cache[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - symfony/framework-bundle v3.3.4 requires symfony/cache ~3.3 -> satisfiable by symfony/cache[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - symfony/framework-bundle v3.3.5 requires symfony/cache ~3.3 -> satisfiable by symfony/cache[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - symfony/framework-bundle v3.3.6 requires symfony/cache ~3.3 -> satisfiable by symfony/cache[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - symfony/framework-bundle v3.3.7 requires symfony/cache ~3.3 -> satisfiable by symfony/cache[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - symfony/framework-bundle v3.3.8 requires symfony/cache ~3.3 -> satisfiable by symfony/cache[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - symfony/framework-bundle v3.3.9 requires symfony/cache ~3.3 -> satisfiable by symfony/cache[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - Can only install one of: symfony/cache[v3.4.0, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.1, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.10, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.11, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.12, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.13, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.14, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.15, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.16, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.17, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.18, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.19, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.2, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.20, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.21, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.22, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.23, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.3, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.4, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.5, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.6, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.7, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.8, v4.2.4].
    - Can only install one of: symfony/cache[v3.4.9, v4.2.4].
    - Can only install one of: symfony/cache[v3.3.0, v4.2.4].
    - Can only install one of: symfony/cache[v3.3.1, v4.2.4].
    - Can only install one of: symfony/cache[v3.3.10, v4.2.4].
    - Can only install one of: symfony/cache[v3.3.11, v4.2.4].
    - Can only install one of: symfony/cache[v3.3.12, v4.2.4].
    - Can only install one of: symfony/cache[v3.3.13, v4.2.4].
    - Can only install one of: symfony/cache[v3.3.14, v4.2.4].
    - Can only install one of: symfony/cache[v3.3.15, v4.2.4].
    - Can only install one of: symfony/cache[v3.3.16, v4.2.4].
    - Can only install one of: symfony/cache[v3.3.17, v4.2.4].
    - Can only install one of: symfony/cache[v3.3.18, v4.2.4].
    - Can only install one of: symfony/cache[v3.3.2, v4.2.4].
    - Can only install one of: symfony/cache[v3.3.3, v4.2.4].
    - Can only install one of: symfony/cache[v3.3.4, v4.2.4].
    - Can only install one of: symfony/cache[v3.3.5, v4.2.4].
    - Can only install one of: symfony/cache[v3.3.6, v4.2.4].
    - Can only install one of: symfony/cache[v3.3.7, v4.2.4].
    - Can only install one of: symfony/cache[v3.3.8, v4.2.4].
    - Can only install one of: symfony/cache[v3.3.9, v4.2.4].
    - Conclusion: don't install smohring/cearch-pro-bundle 1.1.2|don't install symfony/framework-bundle v4.2.4|install symfony/framework-bundle v3.3.0|install symfony/framework-bundle v3.3.1|install symfony/framework-bundle v3.3.10|install symfony/framework-bundle v3.3.11|install symfony/framework-bundle v3.3.12|install symfony/framework-bundle v3.3.13|install symfony/framework-bundle v3.3.14|install symfony/framework-bundle v3.3.15|install symfony/framework-bundle v3.3.16|install symfony/framework-bundle v3.3.17|install symfony/framework-bundle v3.3.18|install symfony/framework-bundle v3.3.2|install symfony/framework-bundle v3.3.3|install symfony/framework-bundle v3.3.4|install symfony/framework-bundle v3.3.5|install symfony/framework-bundle v3.3.6|install symfony/framework-bundle v3.3.7|install symfony/framework-bundle v3.3.8|install symfony/framework-bundle v3.3.9
    - Installation request for symfony/cache (locked at v4.2.4) -> satisfiable by symfony/cache[v4.2.4].
    - Conclusion: don't install smohring/cearch-pro-bundle 1.1.1|don't install symfony/framework-bundle v4.2.4|install symfony/framework-bundle v3.3.0|install symfony/framework-bundle v3.3.1|install symfony/framework-bundle v3.3.10|install symfony/framework-bundle v3.3.11|install symfony/framework-bundle v3.3.12|install symfony/framework-bundle v3.3.13|install symfony/framework-bundle v3.3.14|install symfony/framework-bundle v3.3.15|install symfony/framework-bundle v3.3.16|install symfony/framework-bundle v3.3.17|install symfony/framework-bundle v3.3.18|install symfony/framework-bundle v3.3.2|install symfony/framework-bundle v3.3.3|install symfony/framework-bundle v3.3.4|install symfony/framework-bundle v3.3.5|install symfony/framework-bundle v3.3.6|install symfony/framework-bundle v3.3.7|install symfony/framework-bundle v3.3.8|install symfony/framework-bundle v3.3.9
    - Installation request for smohring/cearch-pro-bundle ^1.1 -> satisfiable by smohring/cearch-pro-bundle[1.1.0, 1.1.1, 1.1.2].
    - Conclusion: don't install symfony/framework-bundle v4.2.4|install symfony/framework-bundle v3.3.0|install symfony/framework-bundle v3.3.1|install symfony/framework-bundle v3.3.10|install symfony/framework-bundle v3.3.11|install symfony/framework-bundle v3.3.12|install symfony/framework-bundle v3.3.13|install symfony/framework-bundle v3.3.14|install symfony/framework-bundle v3.3.15|install symfony/framework-bundle v3.3.16|install symfony/framework-bundle v3.3.17|install symfony/framework-bundle v3.3.18|install symfony/framework-bundle v3.3.2|install symfony/framework-bundle v3.3.3|install symfony/framework-bundle v3.3.4|install symfony/framework-bundle v3.3.5|install symfony/framework-bundle v3.3.6|install symfony/framework-bundle v3.3.7|install symfony/framework-bundle v3.3.8|install symfony/framework-bundle v3.3.9
    - smohring/cearch-pro-bundle 1.1.0 requires symfony/framework-bundle ^3.3 -> satisfiable by symfony/framework-bundle[v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - Can only install one of: symfony/framework-bundle[v3.4.0, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.1, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.10, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.11, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.12, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.13, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.14, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.15, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.16, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.17, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.18, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.19, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.2, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.20, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.21, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.22, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.23, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.3, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.4, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.5, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.6, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.7, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.8, v4.2.4].
    - Can only install one of: symfony/framework-bundle[v3.4.9, v4.2.4].
    - Installation request for symfony/framework-bundle (locked at v4.2.4) -> satisfiable by symfony/framework-bundle[v4.2.4].

[1858.4MiB/41.77s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[646.8MiB/49.35s] Memory usage: 646.78MB (peak: 2054.09MB), time: 49.35s.
[646.8MiB/49.35s] Finished Composer Cloud resolving.


# Cloud Job ID WnGgFWFzqLKhaAZuOm6jz2OYIKRIP0quQ5x72NFZ7L4jozP4ZDn3G8RnqGUxQPoAgjeDGv0eMWC86bXfIn3Pq220zYMhnO7vUsFJeQmXT5EBLKR3BIu failed

---

### The background task has stopped unexpectedly ###
