### ISSUE TITLE
"Test" wird nicht gefunden

### ISSUE THREAD

**Issue by con2net** [smohring/cearch-pro-bundle#6]
Moin, das Suchwort "Test" führt leider zu keinem Ergebnis, obwohl es einige Inhalte gibt, die dieses Wort explizit enthalten ("Blut-Test", "es wurde ein Test durchgeführt"). Wenn der Text "Tests" (also plural) enthält, dann bekomme ich angeboten "meinten sie vielleicht 'Tests'" und diese Artikel werden dann auch angezeigt. Das Wort Test steht definitiv nicht auf der Liste der Stopwörter.
Wenn die Verwendung von csearch ausgeschaltet wird, dann findet die "normale" Contao Suche die obigen Artikel.

Bug oder Feature?

**Comment by max-admina** [comment]
Ich kann das bestätigen.

Standard-Suche: Der Begriff wird gefunden.
Aktivieren der Cearch-Checkbox im Suche-Modul: Der Begriff wird nicht mehr gefunden.

So wäre die Extension leider völlig nutzlos, was sehr sehr schade wäre :(

**Comment by max-admina** [comment]
Korrektur: Ich habe den Suchindex nochmal aufgebaut. Nun findet die Suche die Begriffe doch wieder.

Aber ich kann keines der angepriesenen Features entdecken. Ich sehe nicht, dass es typing errors direkt erkennt? Auch die "Meintest du"-Funktion sehe ich nicht.

**Comment by max-admina** [comment]
Noch eine Korrektur: Habe jetzt gesehen, dass die cearch-Extension eine eigene mod_search.html5 mitbringt. Das habe ich vorher nicht bemerkt, da ich in den Templates nach "cearch" suchte (abgeleitet vom Extension-Namen). Nachdem ich daraus die Anpassungen übernommen in meine eigene modifizierte mod_search.html5 übernommen habe, kommt nun auch der "Meinten Sie"-Part.

Danke, so klappt das :)

**Comment by smohring** [comment]
Schön, dass es geklappt hat - ich schließe das issue damit :)
